#!/usr/bin/env python3
"""Fail if banned typography or LLM-tell wording appears in tracked text.

Two problems, one gate.

The character list is a correctness matter as much as a style one. A
non-breaking hyphen (U+2011) renders identically to ``-`` but breaks grep,
in-repo search and anchor links; 25 of them had crept into words like
``provider-agnostic`` and ``pass-through`` before this check existed. Curly
apostrophes had leaked into code comments and published doc pages the same
way. These characters have no legitimate use here, so there is deliberately
no escape hatch: no pragma, no per-file exemption.

The word list is house style: wording that reads as generated rather than
written. Two tiers, kept separate so they stay independently tunable.

Vendored, generated and data files are out of scope rather than exempted:
we do not author them, so there is nothing to rewrite. See NOT_OURS.

Usage:
    check_prose.py              # every tracked text file
    check_prose.py FILE [...]   # only these paths (how pre-commit calls it)
"""

from __future__ import annotations

import os
import pathlib
import re
import subprocess
import sys
from typing import NamedTuple

# Codepoint -> (name, how to fix it). Written as escapes rather than glyphs so
# the source of the rule cannot itself be the thing that trips it.
BANNED_CHARS: dict[str, tuple[str, str]] = {
    "\u2014": ("em dash", "rephrase with ':' or ',', or split the sentence"),
    "\u2013": ("en dash", "use '-'"),
    "\u2011": ("non-breaking hyphen", "use '-' (this one breaks grep)"),
    "\u2018": ("curly opening quote", 'use "\'"'),
    "\u2019": ("curly apostrophe", 'use "\'"'),
    "\u201c": ("curly opening double quote", "use '\"'"),
    "\u201d": ("curly closing double quote", "use '\"'"),
    "\u00a0": ("non-breaking space", "use a plain space"),
    "\u200b": ("zero-width space", "delete it"),
    "\ufeff": ("byte-order mark", "delete it"),
}

# Deliberately absent, because this project uses them on purpose: emoji (the
# proptest coverage tables), box-drawing, arrows, math and unit symbols,
# ellipsis, bullet, currency.

#: Vocabulary that reads as generated. Low false-positive risk here.
BUZZWORDS: tuple[str, ...] = (
    r"genuine(?:ly)?",
    r"delv(?:e|es|ed|ing)",
    r"seamless(?:ly)?",
    r"meticulous(?:ly)?",
    r"pivotal",
    r"elevat(?:e|es|ed|ing)",
    r"tapestry",
    r"plethora",
    r"myriad",
    r"boasts?",
    r"testament to",
    r"realm of",
    r"worth noting",
    r"cutting-edge",
    r"game-chang(?:er|ing)",
    r"revolution(?:iz|is)(?:e|es|ed|ing)",
)

#: Sentence shapes rather than vocabulary. These are ordinary English, so
#: banning them is a house-style call and not a correctness one. Kept apart
#: from BUZZWORDS so this tier can be relaxed on its own.
HEDGING: tuple[str, ...] = (
    r"it'?s important to note",
    r"it is important to note",
    r"at its core",
    r"in essence",
    r"moreover",
    # `furthermore` is deliberately absent: it appears inside verbatim
    # upstream quotations (e.g. the NNEF 1.0.1 shape_of deprecation note
    # quoted in op/aten/other.py), and with no per-line exemption a ban
    # would force those citations to be misquoted.
    r"that said",
    r"not (?:just|only)\b[^.\n]{1,60}?\bbut\b",
)

# '_' is a word character, so an identifier such as `genuine_hit` is naturally
# unaffected: only prose is matched.
CHAR_RE = re.compile("[" + "".join(BANNED_CHARS) + "]")
WORD_RE = re.compile(
    r"\b(?:" + "|".join(BUZZWORDS + HEDGING) + r")\b", re.IGNORECASE
)

#: Paths we do not author, so there is nothing in them to rewrite. Out of
#: scope, which is not the same as exempted. Our own hand-written demo pages
#: under docs/html/ are deliberately absent from this list: they are ours.
NOT_OURS: tuple[str, ...] = (
    ".min.js",  # vendored uPlot bundle
    ".min.css",
    ".umd.js",  # vendored typed.js bundle
    # wasm-bindgen glue, regenerated by wasm-pack on every build. Each pairs
    # with a <stem>_bg.wasm.
    "docs/html/imageclass_wasm.js",
    "docs/html/llm_wasm.js",
    "docs/html/vad_wasm.js",
    "docs/html/yolo.js",
    # ASR text-normalisation tables, where a word like "revolutionise" is a
    # dictionary key rather than prose.
    "/normalizer/",
)

#: The rule and its fixtures have to spell out every banned word as data, so
#: the word scan would flag itself. Characters are still checked in these two
#: files: BANNED_CHARS is written as \\u escapes precisely so that the char
#: rule needs no exemption anywhere, in these files or any other.
WORDS_EXEMPT: tuple[str, ...] = (
    ".github/scripts/check_prose.py",
    "tests/test_prose_check.py",
)

NUL_SNIFF_BYTES = 8192


class Violation(NamedTuple):
    path: str
    line: int
    col: int
    what: str
    fix: str


def matches(path: str, markers: tuple[str, ...]) -> bool:
    return any(marker in path for marker in markers)


def repo_root() -> pathlib.Path:
    """The worktree root, so the scan does not depend on the caller's cwd."""
    out = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return pathlib.Path(out.strip())


def tracked_files() -> list[str]:
    """Every path git knows about, so untracked files and site/ are excluded.

    ``--full-name`` plus a chdir to the worktree root: plain ``git ls-files``
    lists only what is under the cwd, so running this from a subdirectory would
    silently scan a subset and still report success.
    """
    os.chdir(repo_root())
    out = subprocess.run(
        ["git", "ls-files", "-z", "--full-name"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return [p for p in out.split("\0") if p]


def scan(path: str, check_words: bool = True) -> list[Violation]:
    """Collect violations in one file, or nothing if it is not text."""
    node = pathlib.Path(path)
    # A symlink's hits belong to its target: docs/CHANGELOG.md and friends
    # would otherwise be reported twice, once at a path nobody can edit.
    if node.is_symlink() or not node.is_file():
        return []
    raw = node.read_bytes()
    if b"\0" in raw[:NUL_SNIFF_BYTES]:
        return []  # binary (*.wasm, *.png, ...)
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        # Reporting this as clean would be a silent exemption: a cp1252 file
        # stores an em dash as a single 0x97 byte, so the gate would pass
        # exactly the typography it exists to block. Undecodable text is an
        # error the author has to resolve.
        return [
            Violation(
                path,
                1,
                1,
                "file is not valid UTF-8",
                "re-save as UTF-8 (it cannot be checked otherwise)",
            )
        ]

    found: list[Violation] = []
    for lineno, line in enumerate(text.split("\n"), 1):
        for match in CHAR_RE.finditer(line):
            name, fix = BANNED_CHARS[match.group()]
            what = f"U+{ord(match.group()):04X} {name}"
            found.append(Violation(path, lineno, match.start() + 1, what, fix))
        if not check_words:
            continue
        for match in WORD_RE.finditer(line):
            found.append(
                Violation(
                    path,
                    lineno,
                    match.start() + 1,
                    f"banned wording {match.group()!r}",
                    "rewrite in plain prose",
                )
            )
    return found


def main(argv: list[str]) -> int:
    paths = argv or tracked_files()
    checked = 0
    violations: list[Violation] = []
    for path in paths:
        if matches(path, NOT_OURS):
            continue
        checked += 1
        words = not matches(path, WORDS_EXEMPT)
        violations.extend(scan(path, check_words=words))

    for bad in violations:
        print(
            f"::error file={bad.path},line={bad.line},col={bad.col}"
            f"::{bad.what} -> {bad.fix}"
        )
    if violations:
        files = len({v.path for v in violations})
        print(
            f"\n{len(violations)} prose violation(s) in {files} file(s). "
            "There is no escape hatch for these: fix the text."
        )
        return 1
    print(f"No banned characters or wording across {checked} file(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
