fail_fast: true
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        args: [ --unsafe ]
      - id: check-json
      - id: pretty-format-json
        args: ['--no-sort-keys', '--autofix']
      - id: check-toml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        exclude: tests/
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.0.0
    hooks:
    - id: pyupgrade
      args: ['--py37-plus']
  - repo: git@github.com:PyCQA/prospector.git
    rev: v1.14.1
    hooks:
      - id: prospector
        types: [python]
        args: ['-X']
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check
        entry: uv run ruff check
        args: [--fix]
        language: system
        types: [file, python]
      - id: ruff-format
        name: Ruff format
        entry: uv run ruff format
        language: system
        types: [file, python]
