site_name: documentation
repo_url: https://github.com/sonos/torch-to-nnef
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sonos/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/sonos/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/sonos-inc-/jobs/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - search
  - mkdocs-autoapi:
      autoapi_root: autoapi
      autoapi_dir: torch_to_nnef
      autoapi_ignore:
        - "**/helper.py"
        - "**/quantized.py"
        - "**/aten/*.py"
        - "**/op/custom_extractors/*.py"
        - "**/op/fragment/*.py"
        - "**/peft/*.py"
        - "tests/**"
  - mkdocstrings:
      handlers:
        python:
          paths: [torch_to_nnef]
          options:
            parameter_headings: true

theme:
  name: material
  favicon: img/torch_to_nnef.png
  logo: img/torch_to_nnef.png
  font:
    text: Roboto
  features:
    - navigation.footer
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: white
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white


      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Home: index.md
  - 'Export API': export_api.md
  - Contributing: CONTRIBUTING.md
  - Backstory: backstory.md
  - Changelog: CHANGELOG.md
