import typing as T

import torch

from torch_to_nnef.exceptions import T2NErrorInvalidArgument
from torch_to_nnef.model_wrapper import (
    build_new_names_and_elements,
    build_structured_inputs,
)


class BoundaryAdapter(torch.nn.Module):
    """Boundary adapter applying tuple flattening and collapse at export time.

    Both inputs AND outputs are flattened to flat tensor IO using
    :func:`build_new_names_and_elements`, so that the external interface
    (names, examples, dynamic axes) is always in terms of flat tensors.

    When *outputs_keep* is set the adapter runs one forward pass at
    construction time to discover the output structure, then validates
    *outputs_keep* against the **flattened** output names and filters
    accordingly.
    """

    def __init__(
        self,
        module: torch.nn.Module,
        subnet_name: str,
        input_example: list,
        dynamic_axes: T.Optional[dict[str, dict[int, str]]],
        collapse_by_input: T.Optional[dict[str, set[str]]],
        binds_by_input: T.Optional[dict[str, str]] = None,
        renamed_map: T.Optional[dict[str, list[str]]] = None,
        outputs_keep: T.Optional[list[str]] = None,
        output_collapse_dims: T.Optional[dict[str, list[int]]] = None,
        *,
        apply_symbol_renames: bool = True,
    ) -> None:
        super().__init__()
        self.module = module
        self._orig_input_names = list(getattr(module, "input_names", []) or [])
        self._orig_output_names = list(
            getattr(module, "output_names", []) or []
        )
        orig_input_example = list(input_example or [])
        self._dyn_axes = dict(dynamic_axes or {})
        self._output_collapse_dims = dict(output_collapse_dims or {})
        self._apply_syms = bool(apply_symbol_renames)

        # Flatten inputs using the shared helper.
        (
            initial_ext_names,
            flat_tensors,
            all_flat,
            _tensor_flat,
        ) = build_new_names_and_elements(
            self._orig_input_names,
            orig_input_example,
            default_element_name_tmpl="input_{}",
        )
        self._all_tensor_names: list[str] = list(initial_ext_names)
        self._input_infos = all_flat
        self._flat_example_map: dict[str, object] = dict(
            zip(initial_ext_names, flat_tensors)
        )

        self._init_collapse_indices(
            subnet_name,
            initial_ext_names,
            collapse_by_input or {},
            renamed_map or {},
        )
        self._init_bind_map(
            subnet_name, initial_ext_names, binds_by_input or {}
        )
        self._finalize_external_interface(initial_ext_names)

        # Output flattening is deferred to forward (zero init cost).
        # When outputs_keep is set, outputs are flattened at each
        # forward() call and filtered by name.  No forward pass needed
        # at init — the flat names come from the config (generated by
        # --dump-shape-config) and validated by
        # validate_registry_against_signatures.
        self._outputs_keep: list[str] = list(outputs_keep or [])

    def _init_collapse_indices(
        self,
        subnet_name: str,
        initial_ext_names: list[str],
        collapse_by_input: dict[str, set[str]],
        renamed_map: dict[str, list[str]],
    ) -> None:
        self._collapse_idx: dict[str, list[int]] = {}
        self._rename_map = {
            str(t).upper(): [str(s).upper() for s in (srcs or [])]
            for t, srcs in (renamed_map or {}).items()
        }
        for ext in initial_ext_names:
            q = f"{subnet_name}.{ext}"
            want = set(collapse_by_input.get(q, set()))
            if not want:
                continue
            dyn = self._dyn_axes.get(ext, {})
            drop: list[int] = []
            for i, s in dyn.items():
                su = str(s).upper()
                if su in want:
                    drop.append(i)
                    continue
                for w in want:
                    srcs = self._rename_map.get(w)
                    if srcs and su in srcs:
                        drop.append(i)
                        break
            if drop:
                self._collapse_idx[ext] = sorted(drop)

    def _init_bind_map(
        self,
        subnet_name: str,
        initial_ext_names: list[str],
        binds_by_input: dict[str, str],
    ) -> None:
        self._bind_for_ext: dict[str, tuple[str, str]] = {}
        for ext in list(initial_ext_names):
            q = f"{subnet_name}.{ext}"
            val = binds_by_input.get(q)
            if not isinstance(val, str) or "." not in val:
                continue
            src_q, _, sym = val.rpartition(".")
            src_ext = src_q.split(".", 1)[1] if "." in src_q else src_q
            self._bind_for_ext[ext] = (src_ext, str(sym).strip().upper())

    def _finalize_external_interface(
        self,
        initial_ext_names: list[str],
    ) -> None:
        self._ext_names: list[str] = []
        self._bound_targets: dict[str, tuple[str, str]] = {}
        for ext in initial_ext_names:
            if ext in self._bind_for_ext:
                src_ext, sym = self._bind_for_ext[ext]
                self._bound_targets[ext] = (src_ext, sym)
                continue
            self._ext_names.append(ext)

    @property
    def input_names(self) -> list[str]:
        return list(self._ext_names)

    @property
    def output_names(self) -> list[str]:
        if self._outputs_keep:
            return list(self._outputs_keep)
        return list(self._orig_output_names)

    def _ext_example_for(self, name: str, val) -> object:
        drop = set(self._collapse_idx.get(name, []))
        t = val
        if torch.is_tensor(t) and drop:
            for ax in sorted(drop, reverse=True):
                if 0 <= ax < t.dim():
                    t = t.squeeze(ax) if t.size(ax) == 1 else t.select(ax, 0)
        return t

    def input_example(self):
        out: list[object] = []
        for ext in self._ext_names:
            val = self._flat_example_map.get(ext)
            out.append(self._ext_example_for(ext, val))
        return tuple(out)

    def dynamic_shapes_for_export(self) -> dict[str, dict[int, str]]:
        ext_dyn: dict[str, dict[int, str]] = {}
        for ext in self._ext_names:
            axes = dict(self._dyn_axes.get(ext, {}))
            if not axes:
                continue
            drop = set(self._collapse_idx.get(ext, []))
            if not drop:
                ext_dyn[ext] = axes
                continue
            remap: dict[int, str] = {}
            shift = 0
            for ax in sorted(axes.keys()):
                if ax in drop:
                    shift += 1
                    continue
                remap[ax - shift] = axes[ax]
            if remap:
                ext_dyn[ext] = remap

        # Optionally apply symbol renames (alias sources -> target)
        if self._apply_syms and getattr(self, "_rename_map", None):
            inv: dict[str, str] = {}
            for tgt, srcs in self._rename_map.items():
                for s in srcs:
                    inv[str(s).upper()] = str(tgt).upper()
            renamed: dict[str, dict[int, str]] = {}
            for name, axes in ext_dyn.items():
                mapped: dict[int, str] = {}
                for i, s in axes.items():
                    su = str(s).upper()
                    mapped[i] = inv.get(su, str(s))
                renamed[name] = mapped
            ext_dyn = renamed
        return ext_dyn

    def _compute_bound_value(
        self,
        src_ext: str,
        sym: str,
        ext_val_map: dict[str, object],
    ) -> torch.Tensor:
        """Derive a scalar tensor from a dynamic axis of another input."""
        src_val = ext_val_map.get(src_ext)
        if not torch.is_tensor(src_val):
            raise T2NErrorInvalidArgument(
                f"binding source '{src_ext}' is not a tensor"
            )
        axes = self._dyn_axes.get(src_ext, {})
        old_ax = None
        for i, s in axes.items():
            su = str(s).upper()
            if su == sym:
                old_ax = i
                break
            srcs = self._rename_map.get(sym)
            if srcs and su in srcs:
                old_ax = i
                break
        if old_ax is None:
            raise T2NErrorInvalidArgument(
                f"binding symbol '{sym}' not found on source '{src_ext}'"
            )
        drop = sorted(self._collapse_idx.get(src_ext, []))
        shift = sum(1 for d in drop if d < old_ax)
        new_ax = old_ax - shift
        if not 0 <= new_ax < src_val.dim():
            raise T2NErrorInvalidArgument(
                f"binding axis {new_ax} out of range for '{src_ext}'"
            )
        dim_val = src_val.size(new_ax)
        if torch.is_tensor(dim_val):
            return dim_val.to(dtype=torch.long, device=src_val.device)
        return torch.scalar_tensor(
            dim_val, dtype=torch.long, device=src_val.device
        )

    def _build_flat_tensor_values(self, args: list) -> list:
        """Map external args + bound scalars to a flat tensor list."""
        ext_val_map: dict[str, object] = dict(zip(self._ext_names, args))
        tensor_vals: list = []
        for name in self._all_tensor_names:
            if name in self._bound_targets:
                src_ext, sym = self._bound_targets[name]
                val = self._compute_bound_value(src_ext, sym, ext_val_map)
            else:
                val = ext_val_map[name]
            # Reverse collapse: re-insert squeezed axes
            for ax in sorted(self._collapse_idx.get(name, [])):
                if torch.is_tensor(val):
                    val = val.unsqueeze(ax)
            tensor_vals.append(val)
        return tensor_vals

    def _squeeze_outputs(self, outs):
        """Squeeze configured axes from outputs."""
        if not self._output_collapse_dims:
            return outs
        was_tuple = isinstance(outs, tuple)
        items = outs if was_tuple else (outs,)
        squeezed = list(items)
        for i, name in enumerate(self._orig_output_names):
            if i >= len(squeezed):
                break
            axes = self._output_collapse_dims.get(name)
            if not axes:
                continue
            t = squeezed[i]
            if torch.is_tensor(t):
                for ax in sorted(axes, reverse=True):
                    if 0 <= ax < t.dim() and t.size(ax) == 1:
                        t = t.squeeze(ax)
                squeezed[i] = t
        return tuple(squeezed) if was_tuple else squeezed[0]

    def forward(self, *args, **kwargs):
        assert not kwargs, "BoundaryAdapter expects positional args only"
        tensor_vals = self._build_flat_tensor_values(list(args))
        rebuilt = build_structured_inputs(tensor_vals, self._input_infos)
        outs = self.module(*rebuilt)
        outs = self._squeeze_outputs(outs)

        if not self._outputs_keep:
            return outs

        # Flatten structured outputs and filter by the kept flat names.
        # build_new_names_and_elements is pure Python (no GPU work).
        if isinstance(outs, torch.Tensor):
            outs = (outs,)
        flat_names, flat_tensors, _, _ = build_new_names_and_elements(
            self._orig_output_names,
            outs,
            default_element_name_tmpl="output_{}",
        )
        kept = [
            t
            for n, t in zip(flat_names, flat_tensors)
            if n in self._outputs_keep
        ]
        return tuple(kept)


class RenameOutputs(torch.nn.Module):
    """Wrapper that renames output tensor names for export-time only.

    Leaves computation unchanged and preserves input names.
    Useful to avoid name collisions between inputs and outputs
    (e.g., both named 'length').
    """

    def __init__(self, module: torch.nn.Module, rename_map: T.Dict[str, str]):
        super().__init__()
        self.module = module
        self._rename_map = dict(rename_map or {})

    @property
    def input_names(self):
        return getattr(self.module, "input_names", [])

    @property
    def output_names(self):
        base = list(getattr(self.module, "output_names", []) or [])
        return [self._rename_map.get(n, n) for n in base]

    def dynamic_shapes_for_export(self, *args, **kwargs):
        if hasattr(self.module, "dynamic_shapes_for_export"):
            return self.module.dynamic_shapes_for_export(*args, **kwargs)
        return {}

    def forward(self, *args, **kwargs):
        return self.module(*args, **kwargs)
