"""Some Core PyTorch core naming, used to trace/parse their JIT."""

PRIM_STARTID = "prim::"
CALL_KIND = "prim::CallMethod"
CONSTANT_KIND = "prim::Constant"
DATA_KIND = "prim::data"
DEVICE_KIND = "prim::device"
DICTCONSTRUCT_KIND = "prim::DictConstruct"
DTYPE_KIND = "prim::dtype"
GETATTR_KIND = "prim::GetAttr"
IF_KIND = "prim::If"
LISTCONSTRUCT_KIND = "prim::ListConstruct"
LISTUNPACK_KIND = "prim::ListUnpack"
LOOP_KIND = "prim::Loop"
NUMTOTENSOR_KIND = "prim::NumToTensor"
PARAM_KIND = "prim::Param"
RAISE_EXCEPTION_KIND = "prim::RaiseException"
TUPLECONSTRUCT_KIND = "prim::TupleConstruct"
TUPLEINDEX_KIND = "prim::TupleIndex"
TUPLEUNPACK_KIND = "prim::TupleUnpack"

ATEN_STARTID = "aten::"
ATEN_ADD = "aten::add"
ATEN_ADD_ = "aten::add_"
ATEN_ALIAS = "aten::alias"
ATEN_ARANGE = "aten::arange"
ATEN_BADDMM = "aten::baddbmm"
ATEN_BOOL = "aten::Bool"
ATEN_CLONE = "aten::clone"
ATEN_CONTAINS = "aten::__contains__"
ATEN_CONTIGUOUS_KIND = "aten::contiguous"
ATEN_CONV1D = "aten::conv1d"
ATEN_CONV2D = "aten::conv2d"
ATEN_CONV3D = "aten::conv3d"
ATEN_CONVOLUTION = "aten::convolution"
ATEN_CONVOLUTION_BARE = "aten::_convolution"
ATEN_CONVOLUTION_MODE = "aten::_convolution_mode"
ATEN_CUMSUM = "aten::cumsum"
ATEN_DIM = "aten::dim"
ATEN_DIV = "aten::div"
ATEN_DIV_ = "aten::div_"
ATEN_EINSUM = "aten::einsum"
ATEN_ELU = "aten::elu"
ATEN_EMPTY = "aten::empty"
ATEN_EMPTY_LIKE = "aten::empty_like"
ATEN_EMBEDDING = "aten::embedding"
ATEN_EQ = "aten::eq"
ATEN_EXPAND = "aten::expand"
ATEN_FLOAT = "aten::Float"
ATEN_FORMAT = "aten::format"
ATEN_FULL = "aten::full"
ATEN_FULL_LIKE = "aten::full_like"
ATEN_GE = "aten::ge"
ATEN_GELU = "aten::gelu"
ATEN_GETITEM = "aten::__getitem__"
ATEN_GT = "aten::gt"
ATEN_INT = "aten::Int"
ATEN_LE = "aten::le"
ATEN_LEN = "aten::len"
ATEN_LINALG_NORM = "aten::linalg_norm"
ATEN_LINALG_VECTOR_NORM = "aten::linalg_vector_norm"
ATEN_LINEAR = "aten::linear"
ATEN_LT = "aten::lt"
ATEN_MASKED_FILL = "aten::masked_fill"
ATEN_MASKED_FILL_ = "aten::masked_fill_"
ATEN_MATMUL = "aten::matmul"
ATEN_MEAN = "aten::mean"
ATEN_MUL = "aten::mul"
ATEN_MUL_ = "aten::mul_"
ATEN_NE = "aten::ne"
ATEN_NEW_EMPTY = "aten::new_empty"
ATEN_NEW_ONES = "aten::new_ones"
ATEN_NEW_ZEROS = "aten::new_zeros"
ATEN_NOT = "aten::__not__"
ATEN_NUMEL = "aten::numel"
ATEN_ONES = "aten::ones"
ATEN_ONES_LIKE = "aten::ones_like"
ATEN_PROD = "aten::prod"
ATEN_RELU = "aten::relu"
ATEN_REPEAT_INTERLEAVE = "aten::repeat_interleave"
ATEN_SCALARIMPLICIT = "aten::ScalarImplicit"
ATEN_SCALAR_TENSOR = "aten::scalar_tensor"
ATEN_SCALED_DOT_PRODUCT_ATTENTION = "aten::scaled_dot_product_attention"
ATEN_SELECT = "aten::select"
ATEN_SILU = "aten::silu"
ATEN_SIZE_KIND = "aten::size"
ATEN_STR = "aten::str"
ATEN_SUB = "aten::sub"
ATEN_SUB_ = "aten::sub_"
ATEN_SUM = "aten::sum"
ATEN_TO = "aten::to"
ATEN_TO_COPY = "aten::_to_copy"
ATEN_TRIL_INDICES = "aten::tril_indices"
ATEN_TRIU_INDICES = "aten::triu_indices"
ATEN_VANDER = "aten::vander"
ATEN_VIEW_KIND = "aten::view"
ATEN_WHERE = "aten::where"
ATEN_ZEROS = "aten::zeros"
ATEN_ZERO_LIKE = "aten::zeros_like"
ATEN_BARTLETT_WINDOW = "aten::bartlett_window"
ATEN_LOGSPACE = "aten::logspace"


CLASSTYPE_KIND = "ClassType"
TUPLETYPE_KIND = "TupleType"
LISTTYPE_KIND = "ListType"
NONETYPE_KIND = "NoneType"
INTTYPE_KIND = "IntType"
FLOATTYPE_KIND = "FloatType"
BOOLTYPE_KIND = "BoolType"
STRINGTYPE_KIND = "StringType"
NUMBERTYPE_KIND = "NumberType"  # This type represents a Python number
DICTTYPE_KIND = "DictType"
TENSORTYPE_KIND = "TensorType"
OPTIONALTYPE_KIND = "OptionalType"
# Subtype hierarchy for Number Types (NumberType as the base type):
# IntType <: NumberType
# FloatType <: NumberType
# ComplexType <:NumberType

MODULE_PATH_ATEN = "TORCH_INTERNAL_ATEN"
MODULE_PATH_QUANTIZED = "TORCH_INTERNAL_QUANTIZED"
SPECIAL_ATEN_REMAP_PYTORCH = {"__and__": "bitwise_and", "__or__": "bitwise_or"}

WIRED_CUSTOM_LSTM = "wired_custom::LSTM"
WIRED_CUSTOM_LSTM_CELL = "wired_custom::LSTMCell"

MAP_TO_NOP = [
    NUMTOTENSOR_KIND,
    LISTCONSTRUCT_KIND,
    ATEN_SCALARIMPLICIT,
    ATEN_ALIAS,
]
MAP_TO_TENSOR_FN = [ATEN_CONTIGUOUS_KIND, ATEN_VIEW_KIND]
