[workspace]
resolver = "3"

members = ["./src/nemo_asr/", "./src/nemo_asr_ffi", "src/nemo_asr_ffi"]

[workspace.dependencies]
anyhow = "1.0"
env_logger = "0.11"
itertools = "0.14"
log = "0.4"
libc = "0.2"
ffi-convert = "0.7"
hound = "3.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
test-log = "0.2.21"
tract-rs = { git = "https://github.com/sonos/tract.git", rev = "c484b3e" }
# have to be aligned with tract version above
ndarray-npy = { version = "0.10.0", features = ["compressed_npz"] }

[profile.release]
debug = true
