[package]
name = "vad-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
# tract-rs = { git = "https://github.com/sonos/tract.git", rev = "a9b3989" }
tract-rs = { git = "https://github.com/sonos/tract.git", rev = "d2b358f", default-features = false }
tract-onnx-opl = { git = "https://github.com/sonos/tract.git", rev = "d2b358f", features = [
    "getrandom-js",
] }
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.6"
web-sys = { version = "0.3", features = ["console"] }
anyhow = "1.0"
console_error_panic_hook = "0.1"

[features]
default = []
log-vad = []

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[dev-dependencies]
hound = "3.5"
lewton = "0.10" # optional; reserved for future ogg/vorbis if needed
