[package]
name = "vad-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
tract-rs = { git = "https://github.com/sonos/tract.git", rev = "a9b3989" }
# tract-rs = { path = "/Users/julien.balian/SONOS/src/tract/api/rs" }
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.6"
web-sys = { version = "0.3", features = ["console"] }
anyhow = "1.0"
