[project]
name = "t2n-example-yolo"
version = "0.0.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    "torch_to_nnef",
    "torch==2.1.2",
    "numpy==1.26.4",
    "onnx==1.20.1",
    "ultralytics==8.4.15",
]

[tool.uv]
package = false

[tool.uv.sources]
torch_to_nnef = { path = "../../", editable = true }
