[package]
name = "nemo_asr_ffi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]
name = "nemo_asr_ffi"

[dependencies]
nemo_asr = { path = "../nemo_asr" }
anyhow = { workspace = true }
env_logger = { workspace = true }
ffi-convert = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
