[project]
name = "t2n-example-multi-io-py"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = [
    "torch_to_nnef",
    "torch==2.7.0",
    "transformers==4.53.2",
    "sentencepiece==0.2.1",
]

[tool.uv]
package = false

[tool.uv.sources]
torch_to_nnef = { path = "../../", editable = true }
