name: core CI

on:
  push:
    branches: [main]
    paths:
      - "torch_to_nnef/**"
      - "tests/**"
      - "packages/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/ci-core.yml"
  pull_request:
    branches: [main]
    paths:
      - "torch_to_nnef/**"
      - "tests/**"
      - "packages/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/ci-core.yml"
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Create matrix
        id: create_matrix
        uses: fabiocaccamo/create-matrix-action@842c9dabf1cec0ba7417f30ec26ce2290b951ef0 # v7
        with:
          matrix: |
            python-version {3.10}, tox-env {"torch_1_13"}
            python-version {3.12}, tox-env {"torch_2_2", "zoo_torch_2_2"}
            python-version {3.13}, tox-env {"py313", "zoo_py313", "proptest", "format_check", "static_check", "silero_vad_demo"}
            python-version {3.14}, tox-env {"py314", "zoo_py314"}

    outputs:
      matrix: ${{ steps.create_matrix.outputs.matrix }}

  test:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.prepare.outputs.matrix)}}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox==4.23.2

      - name: test with tox
        run: tox run -e ${{ matrix.tox-env }}
