name: NeMo CI

on:
  push:
    branches: [main]
    paths:
      - "packages/nemo-asr/**"
      - "torch_to_nnef/**"
  pull_request:
    branches: [main]
    paths:
      - "packages/nemo-asr/**"
      - "torch_to_nnef/**"
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create matrix
        id: create_matrix
        uses: fabiocaccamo/create-matrix-action@v3
        with:
          matrix: |
            python-version {3.12}, tox-env {"nemo_tract_2_0_0", "nemo_tract_2_5_3"}

    outputs:
      matrix: ${{ steps.create_matrix.outputs.matrix }}

  test:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.prepare.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox==4.23.2

      - name: test with tox
        run: cd packages/nemo-asr && tox run -e ${{ matrix.tox-env }}
