name: Deploy T2N docs

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths:
      - "**.md"
      - "mkdocs.yml"
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email sonos+github-actions[bot]@users.noreply.github.com

      - name: Register the personal access token
        run: echo "${{ secrets.T2N_GITHUB_TOKEN }}" | gh auth login --with-token
      - name: Configure the Git credential helper
        run: gh auth setup-git

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12


      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true


      - name: Install dependencies
        run: |
          uv sync --group dev

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-

      - name: Deploy to GitHub Pages
        run: |
          gh auth login
          uv run mkdocs gh-deploy --force
        env:
          GH_TOKEN: ${{ secrets.T2N_GITHUB_TOKEN }}
